//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Independiente.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las credenciales ingresadas no son válidas. Verifique su nombre de usuario y contraseña e inténtelo de nuevo.
        /// </summary>
        public static string CredentialsNotFoundMessage {
            get {
                return ResourceManager.GetString("CredentialsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ciudad es inválida. Solo se permiten letras, espacios y guiones..
        /// </summary>
        public static string InvalidCityMessage {
            get {
                return ResourceManager.GetString("InvalidCityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La CLABE debe tener 18 digitos..
        /// </summary>
        public static string InvalidCLABEMessage {
            get {
                return ResourceManager.GetString("InvalidCLABEMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CURP es inválido. Debe seguir el siguiente formato: 4 letras + 6 dígitos + H/M + 2 letras + 5 alfanuméricos..
        /// </summary>
        public static string InvalidCURPMessage {
            get {
                return ResourceManager.GetString("InvalidCURPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa un correo electrónico válido con el formato usuario@dominio.com. Asegúrate de que no contenga espacios, no supere los 50 caracteres y tenga un símbolo &apos;@&apos; y un dominio válido..
        /// </summary>
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo debe contener letras (A-Z, áéíóú, ñ, ü) y espacios/apóstrofes. Además debe tener una longitud mínima de 2 caracteres y máximo 50..
        /// </summary>
        public static string InvalidNameMessage {
            get {
                return ResourceManager.GetString("InvalidNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La colonia es inválida. Solo se permiten letras, números, espacios, -, . y ,.
        /// </summary>
        public static string InvalidNeighborhoodMessage {
            get {
                return ResourceManager.GetString("InvalidNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada no cumple con los criterios de seguridad. Asegúrese de contenga entre 8 y 32 caracteres, una letra mayúscula, un número y un carácter especial (!, @, $, %, *)”.
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teléfono es inválido. Debe tener el siguiente formato: 10 dígitos (opcionalmente con código de país +52 o lada entre paréntesis) y con guiones, espacios o paréntesis opcionales..
        /// </summary>
        public static string InvalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC es inválido. Debe seguir el siguiente formato: 4 letras + 6 dígitos + 3 alfanuméricos..
        /// </summary>
        public static string InvalidRFCMessage {
            get {
                return ResourceManager.GetString("InvalidRFCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La calle es inválida. Solo se permiten letras, números, espacios, #, -, ., y ,.
        /// </summary>
        public static string InvalidStreetMessage {
            get {
                return ResourceManager.GetString("InvalidStreetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos solo deben contener letras (A-Z, áéíóú, ñ, ü) y espacios/apóstrofes. Además deben tener una longitud mínima de 2 caracteres y máximo 50..
        /// </summary>
        public static string InvalidSurnameMessage {
            get {
                return ResourceManager.GetString("InvalidSurnameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea cerrar sesión?.
        /// </summary>
        public static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un banco de la lista..
        /// </summary>
        public static string NoBankSelectedMessage {
            get {
                return ResourceManager.GetString("NoBankSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un estado de la lista.
        /// </summary>
        public static string NoStateSelectionMessage {
            get {
                return ResourceManager.GetString("NoStateSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por políticas de la empresa, no se pueden otorgar créditos a mayores de 60 años.
        /// </summary>
        public static string OverSixtyYearsMessage {
            get {
                return ResourceManager.GetString("OverSixtyYearsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de telefono y el numero de telefono alternativo deben ser diferentes. .
        /// </summary>
        public static string PhoneNumberIsRepeated {
            get {
                return ResourceManager.GetString("PhoneNumberIsRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC ingresado ya está registrado en el sistema.
        /// </summary>
        public static string RFCRegisteredMessage {
            get {
                return ResourceManager.GetString("RFCRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente debe tener al menos 18 años para solicitar un crédito..
        /// </summary>
        public static string UnderEighteenYearsMessage {
            get {
                return ResourceManager.GetString("UnderEighteenYearsMessage", resourceCulture);
            }
        }

        public static string IncompleteDocumentationMessage
        {
            get
            {
                return ResourceManager.GetString("IncompleteDocumentationMessage", resourceCulture);
            }
        }

        public static string InvalidMoneyMessage
        {
            get
            {
                return ResourceManager.GetString("InvalidMoneyMessage", resourceCulture);
            }
        }

        public static string InvalidRoleMessage
        {
            get
            {
                return ResourceManager.GetString("InvalidRoleMessage", resourceCulture);
            }
        }

        public static string InvalidDateMessage
        {
            get
            {
                return ResourceManager.GetString("InvalidDateMessage", resourceCulture);
            }
        }

        public static string ClientRegistrationError
        {
            get
            {
                return ResourceManager.GetString("ClientRegistrationError", resourceCulture);
            }
        }        
    }
}
