//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Relationships {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Relationships() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Independiente.Properties.Relationships", typeof(Relationships).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tia.
        /// </summary>
        internal static string Aunt {
            get {
                return ResourceManager.GetString("Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermano.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primo/Prima.
        /// </summary>
        internal static string Cousin {
            get {
                return ResourceManager.GetString("Cousin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hija.
        /// </summary>
        internal static string Daughter {
            get {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Padre.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abuelo.
        /// </summary>
        internal static string Grandfather {
            get {
                return ResourceManager.GetString("Grandfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abuela.
        /// </summary>
        internal static string Grandmother {
            get {
                return ResourceManager.GetString("Grandmother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esposo.
        /// </summary>
        internal static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madre.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo.
        /// </summary>
        internal static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tio.
        /// </summary>
        internal static string Uncle {
            get {
                return ResourceManager.GetString("Uncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esposa.
        /// </summary>
        internal static string Wife {
            get {
                return ResourceManager.GetString("Wife", resourceCulture);
            }
        }
    }
}
