//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeView
    {
        public string CLABE { get; set; }
        public string ClientName { get; set; }
        public string Lastname { get; set; }
        public string Surname { get; set; }
        public string BankName { get; set; }
        public int PaymentNumber { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal FixedPayment { get; set; }
        public decimal Interest { get; set; }
        public decimal OutstandingBalance { get; set; }
        public string Status { get; set; }
        public int CreditId { get; set; }
    }
}
