//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientView
    {
        public string CLABE { get; set; }
        public int BankId { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public string Neighborhood { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientLastname { get; set; }
        public string ClientSurname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string ClientPhoneNumber { get; set; }
        public string ClientEmail { get; set; }
        public string FirstReferenceName { get; set; }
        public string FirstReferenceLastname { get; set; }
        public string FirstReferencePhoneNumber { get; set; }
        public string FirstReferenceRelationship { get; set; }
        public string FirstReferenceEmail { get; set; }
        public string SecondReferenceName { get; set; }
        public string SecondReferenceLastname { get; set; }
        public string SecondReferencePhoneNumber { get; set; }
        public string SecondReferenceRelationship { get; set; }
        public string SecondReferenceEmail { get; set; }
        public string WorkCenterName { get; set; }
        public string Role { get; set; }
        public System.DateTime HiringDate { get; set; }
        public decimal MontlyIncome { get; set; }
        public Nullable<int> SecondReference { get; set; }
        public Nullable<int> FirstReference { get; set; }
        public int AddressDataId { get; set; }
        public int PersonalDataId { get; set; }
        public int WorkCenterId { get; set; }
        public int AccountId { get; set; }
    }
}
