//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditPolicy()
        {
            this.Report_CreditPolicy = new HashSet<Report_CreditPolicy>();
        }
    
        public int CreditPolicyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_CreditPolicy> Report_CreditPolicy { get; set; }
    }
}
