//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int CreditId { get; set; }
        public System.DateTime AcceptanceDate { get; set; }
        public string Status { get; set; }
        public int CreditApplicationId { get; set; }
    }
}
