//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditApplicationListView
    {
        public int CreditApplicationId { get; set; }
        public decimal LoanAmount { get; set; }
        public System.DateTime LoanApplicationDate { get; set; }
        public string Status { get; set; }
        public int ClientId { get; set; }
        public int FileId { get; set; }
        public int PromotionalOfferId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Lastname { get; set; }
        public string RFC { get; set; }
    }
}
