//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public string Role { get; set; }
        public string Password { get; set; }
        public int UserId { get; set; }
        public int AddressDataId { get; set; }
        public int PersonalDataId { get; set; }
        public string Status { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Department { get; set; }
        public string NSS { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Surname { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public string Neighborhood { get; set; }
    }
}
