//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string NSS { get; set; }
        public string Department { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Status { get; set; }
        public int PersonalDataId { get; set; }
        public int AddressDataId { get; set; }
        public int UserId { get; set; }
    
        public virtual AddressData AddressData { get; set; }
        public virtual PersonalData PersonalData { get; set; }
        public virtual User User { get; set; }
    }
}
