//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndependienteEntities : DbContext
    {
        public IndependienteEntities()
            : base("name=IndependienteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AddressData> AddressData { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<CreditApplication> CreditApplication { get; set; }
        public virtual DbSet<CreditPolicy> CreditPolicy { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<PersonalData> PersonalData { get; set; }
        public virtual DbSet<PromotionalOffer> PromotionalOffer { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkCenter> WorkCenter { get; set; }
        public virtual DbSet<AmortizationSchedule> AmortizationSchedule { get; set; }
        public virtual DbSet<Report_CreditPolicy> Report_CreditPolicy { get; set; }
        public virtual DbSet<ClientView> ClientView { get; set; }
        public virtual DbSet<EmployeeView> EmployeeView { get; set; }
    }
}
