//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int EmployeeId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int BankId { get; set; }
        public int TotalCredits { get; set; }
        public int ActualCredits { get; set; }
        public string Status { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
