//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_CreditPolicy
    {
        public int ReportId { get; set; }
        public int CreditPolicyId { get; set; }
    
        public virtual CreditPolicy CreditPolicy { get; set; }
        public virtual Report Report { get; set; }
    }
}
